### ISSUE TITLE
[RPC] Introduce a rust RPC framework

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#10]
We need to choose a rust RPC framework and consider the following requirements.

1. It can run a standalone server.
2. It can easily be embedded into another system(MoveOS also is a library).
3. Javascript SDK friendly, REST or JSON-RPC?

## Dependency
#11

**Comment by lshoo** [comment]
In rust language, RPC has more star in github are [jsonrpc](https://github.com/paritytech/jsonrpc) and [jsonrpsee](https://github.com/paritytech/jsonrpsee), and jsonrpsee is the successor of the former, and they are both produced by ParirtyTech

**Comment by pause125** [comment]
jsonrpsee is so new, is it stable enough?

**Comment by lshoo** [comment]
> jsonrpsee is so new, is it stable enough?

jsonrpsee used in Subsbtrate, Sui.
Or what better options are available

**Comment by pause125** [comment]
> > jsonrpsee is so new, is it stable enough?
> 
> jsonrpsee used in Subsbtrate, Sui. Or what better options are available

If jsonsee is stable enough, it's offcause a good choice. I 'm not familiar with RPC Frameworks.

**Comment by lshoo** [comment]
Add another option: [tarpc](https://github.com/google/tarpc), 25k stars in github,  the `Distributed tracing` feature is useful:
tarpc differentiates itself from other RPC frameworks by defining the schema in code,
rather than in a separate language such as .proto. This means there's no separate compilation
process, and no context switching between different languages.

Some other features of tarpc:
- Pluggable transport: any type implementing `Stream<Item = Request> + Sink<Response>` can be
  used as a transport to connect the client and server.
- `Send + 'static` optional: if the transport doesn't require it, neither does tarpc!
- Cascading cancellation: dropping a request will send a cancellation message to the server.
  The server will cease any unfinished work on the request, subsequently cancelling any of its
  own requests, repeating for the entire chain of transitive dependencies.
- Configurable deadlines and deadline propagation: request deadlines default to 10s if
  unspecified. The server will automatically cease work when the deadline has passed. Any
  requests sent by the server that use the request context will propagate the request deadline.
  For example, if a server is handling a request with a 10s deadline, does 2s of work, then
  sends a request to another server, that server will see an 8s deadline.
- Distributed tracing: tarpc is instrumented with
  [tracing](https://github.com/tokio-rs/tracing) primitives extended with
  [OpenTelemetry](https://opentelemetry.io/) traces. Using a compatible tracing subscriber like
  [Jaeger](https://github.com/open-telemetry/opentelemetry-rust/tree/main/opentelemetry-jaeger),
  each RPC can be traced through the client, server, and other dependencies downstream of the
  server. Even for applications not connected to a distributed tracing collector, the
  instrumentation can also be ingested by regular loggers like
  [env_logger](https://github.com/env-logger-rs/env_logger/).
- Serde serialization: enabling the `serde1` Cargo feature will make service requests and
  responses `Serialize + Deserialize`. It's entirely optional, though: in-memory transports can
  be used, as well, so the price of serialization doesn't have to be paid when it's not needed.
