### ISSUE TITLE
[DA] Data Namespacing

### ISSUE THREAD

**Issue by bytedeveloperr** [rooch-network/rooch#1053]
_Re @popcnt-subodhi in https://github.com/rooch-network/rooch/issues/1031#issuecomment-1778432654_

PS: I assume that @popcnt-subodhi was referring to "blobs" rather than "files."

Yeah, Celestia uses the concept of namespaces for storing and retrieving blobs. This method allows for a structured arrangement of the data and could potentially enhance the efficiency of access, which is desired in a network like Rooch.

A namespace is composed of two parts, each represented in bytes:
- `version`: a byte representing the version of the namespace
- `id`: a 28-byte value representing the unique id of the namespace

The namespaces are unique to applications - they are not shared, thereby enabling the applications to function and operate independently without cross-interference from other applications.

This concept could be adopted by Rooch as well; I envision each L1 having its distinct namespace, with only the data relevant to the L1 being written to that namespace. This arrangement would enable a more orderly storage and reduce clutter.

For instance, data pertaining to Ethereum and Bitcoin should be recorded within their own individual namespaces, without any cross-interactions.

This is just a basic outline, there's much more to explore beyond this.

cc @jolestar

**Comment by jolestar** [comment]
Data from Ethereum or Bitcoin will be represented as rooch transactions in rooch, so there's no need to distinguish that. 

But Rooch also allows developers to build their own sovereign rollups, and the namespace of each sovereign rollup should be different.

**Comment by popcnt-subodhi** [comment]
> _Re @popcnt-subodhi in [#1031 (comment)](https://github.com/rooch-network/rooch/issues/1031#issuecomment-1778432654)_
> 
> PS: I assume that @popcnt-subodhi was referring to "blobs" rather than "files."
> 
> Yeah, Celestia uses the concept of namespaces for storing and retrieving blobs. This method allows for a structured arrangement of the data and could potentially enhance the efficiency of access, which is desired in a network like Rooch.
> 
> A namespace is composed of two parts, each represented in bytes:
> 
> * `version`: a byte representing the version of the namespace
> * `id`: a 28-byte value representing the unique id of the namespace
> 
> The namespaces are unique to applications - they are not shared, thereby enabling the applications to function and operate independently without cross-interference from other applications.
> 
> This concept could be adopted by Rooch as well; I envision each L1 having its distinct namespace, with only the data relevant to the L1 being written to that namespace. This arrangement would enable a more orderly storage and reduce clutter.
> 
> For instance, data pertaining to Ethereum and Bitcoin should be recorded within their own individual namespaces, without any cross-interactions.
> 
> This is just a basic outline, there's much more to explore beyond this.
> 
> cc @jolestar

@bytedeveloperr 

1. blob: Yes, it is a blob storage with a key-value structure
2. namespacing: For each rooch network, we only have single namespace

I mentioned namespace earlier mainly because I was concerned about the differences in the specific implementations of the different da's for building kv indexes. celestia builds the key from the version-id, which is one way to do it. There may be other ways (e.g. some kind of digest). There are two problems we face when trying to merge the various da's:

1. relay nodes serve (our DA server for connect sequencer/verifier/others to DA backend) data in a uniform way
2. when the relay node finishes transmitting data to the DA, it should pass back to layer2 the direct access method of the corresponding DA (the current idea is to initiate a rooch tx to record it). This will enable stateless replacement of the relay
