### ISSUE TITLE
[MoveVerifier] entry function verifier

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#152]
Implement verifier extension for entry function.

verifier the entry function parameter type and return type

### Ref

#148

**Comment by steelgeek091** [comment]
Should we put this issue and its code solution together with the resolution for issue #64?

**Comment by jolestar** [comment]
It is a verifier requirement, but the entry function does not need an annotation.

**Comment by steelgeek091** [comment]
In this link, https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/framework/src/extended_checks.rs#L116, the logic for checking the entry function is exactly what we need (I think), because it also checks the parameter types for the entry function to see if they are the specified types (without checking the entry function's annotations).

The code and analysis for the annotation and metadata generation of the entry function are placed together in the above code section, https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/framework/src/extended_checks.rs#L69. My point is, if we want to quickly solve the problem with the entry function, can't we use this method first, instead of adding a new verifier to the Move codebase, as adding a new verifier would require modifications to the Move code.
