### ISSUE TITLE
[API] Refactoring the return type of the `getEventsByEventHandle` interface

### ISSUE THREAD

**Issue by wubuku** [rooch-network/rooch#264]
The interface for pulling events now directly returns an array (Vec). Then, when pulling the next page, the cursor parameter passed in is "the event seq. number of the last item of the pull result, plus 1". i.e.:

```
next_cursor = last seq_number + 1
```

Because the sequence number of the first event record is 0, the result of "not passing in the cursor parameter" is the same as "passing in 0".

It feels like this “+1” operation developers may forget. I don’t know if it is more natural to directly pass the sequence number of ”the last record of“ the current page? I have the impression that Sui RPC API’s approach is like this.

Moreover, Sui returns a Page structure for similar pagination access interfaces, roughly like this (Java pseudocode):

```java
public class Page<T, C> {
    private List<T> data;

    private C nextCursor;

    private Boolean hasNextPage;
    //...
}
```

In this way, developers don’t need to think about whether to "plus 1” to get `next_cursor` or not.

The advantage of providing a hasNextPage is that sometimes, the developer don't need to pull one more time, i.e., they don't need to "pull until the empty list is returned", to know that "there is no next page".

The advantage of using "seq. number/ ID of the last record" for a cursor is that the processing logic is more consistent.

In the Java pseudo-code above, the cursor is a generic type, which means that for some types of cursors, it is not always possible to calculate the ID of the next record based on the "ID of the last record".

For example, if the cursor type is a UUID, we can only know what the ID of the last record is, but we cannot deduce what the UUID of the next record is.

So, consider introducing a `Page<T>` structure into the RPC APIs implementation and refactoring the `getEventsByEventHandle` function.

**Comment by baichuan3** [comment]
Previously in pr https://github.com/rooch-network/rooch/pull/177, the json response was removed, and the standard jsonrpc return was followed.

The problem now is that the expected `the Page structure` does not comply with the standard jsonrpc format. In order to be compatible with page-turning queries, the interface needs to be adjusted to return as follows:

1) All interface returns use a new format, and a layer of data is nested in the result to represent the returned data. The data may be a json array or json data.
If it is a page-turning query, `next_cursor` is additionally returned. When next_cursor is 0 or null, it means that there is no new data, and the caller can end the query.

```
{
     "jsonrpc": "2.0",
     "result": {
         "data": [
             {
             },
          ]
          "next_cursor": 101
     }
}
```

2) cursor supports the following types of MoveValue types:

```
pub enum MoveValue {
     U8(u8),
     U64(u64),
     U128(u128),
     Bool(bool),
     Address(AccountAddress),
     Vector(Vec<MoveValue>),
     Struct(MoveStruct),
     Signer(AccountAddress),
     // NOTE: Added in bytecode version v6, do not reorder!
     U16(u16),
     U32(u32),
     U256(u256::U256),
}
```

next_cursor returns using MoveValueAnnotator
