### ISSUE TITLE
[Framework & Stdlib] Unify self and this in Move module

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#324]
Some modules we use `this` and some modules we use `self`, need to be unified.

https://github.com/rooch-network/rooch/blob/ca178fe2e0a96a41167fda24b405b391ff56637d/crates/rooch-framework/sources/authenticator.move#L63-L87

https://github.com/rooch-network/rooch/blob/ca178fe2e0a96a41167fda24b405b391ff56637d/moveos/moveos-stdlib/moveos-stdlib/sources/storage_context.move#L46-L71

**Comment by feliciss** [comment]
🙋‍♀️

**Comment by feliciss** [comment]
I think we should use `Self` instead of `This`, reasons as below:

1. According to the Move guide: https://move-language.github.io/move/uses.html. It is suggested to use `Self` as aliases:

> If you need to add an alias to the Module itself in addition to module members, you can do that in a single use using Self. Self is a member of sorts that refers to the module.

2. In your latest commit, you used `Self` not `This` for add and get methods in [storage_context.move](https://github.com/rooch-network/rooch/blob/ca178fe2e0a96a41167fda24b405b391ff56637d/moveos/moveos-stdlib/moveos-stdlib/sources/storage_context.move#L46-L71) file.

3. From my understanding, Move is much similar to Rust in linguistic contexts, so it should be used as `Self` instead of `This`.
