### ISSUE TITLE
[Indexer] determine and implement indexer db

### ISSUE THREAD

**Issue by baichuan3** [rooch-network/rooch#430]
PostgreSQL vs Sqlite

1. Sqlite is embedded and does not require additional installation of Server, which will reduce the installation cost of developers. However, Sqlite does not support data partitioning, and there is a scalability limit for large-capacity data.
2. PostgreSQL has relatively complete functions. Both Sui and Aptos Indexer choose PostgreSQL, which requires additional installation, which can be regarded as one of the later expansion options.

Among them, GraphQL supports both PostgreSQL and Sqlite as endpoints.

It was decided to choose Sqlite as the Indexer DB in the early stage, and later upgrade to PostgreSQL depending on the Indexer needs.

Choose diesel as the ORM operation database.

**Comment by wubuku** [comment]
Using the embedded SQL database doesn't seem to ease the issue of cross-database transaction processing.

Rooch Server includes a "complex" indexer, which I actually wonder if this is a move in the right direction?

If there is no "good" indexer, as an application developer, the solution I would use is to emit domain events at the application level (even if there is a "good" indexer, there is nothing wrong with adding the code for emitting domain events in the contracts first), then the off-chain service subscribes/pulls the events and updates the local database with the on-chain state.

Of course, if we want to make a generic indexer, then we can't rely on "domain events".

But we can emit some underlying events at a slightly lower level. (Note that these events are different from the events emitted in the Move contract.)

These events may include `insert`, `update`, `delete` operation information on the K/V database; and some additional Move contract-level metadata (e.g., the current insert operation is adding an `Object<Article>` or something like that).

Rooch Server can then expose such an event subscription/pull interface, turning the indexer into a standalone development project. Let anyone implement a relatively generic indexer in any language.

The ops issue caused by one more service can be mitigated by Docker and other wrapper solutions.

@jolestar

**Comment by jolestar** [comment]
Discussion: https://discord.com/channels/1078938449974935592/1126800552546811936

**Comment by jolestar** [comment]
tracked with #384
