### ISSUE TITLE
[Multichain] multi-chain address to Rooch address

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#449]
I think creating a new address in the resolve function is not a good idea because we can not ensure that the address mapping exists via the resolve function.

_Originally posted by @jolestar in https://github.com/rooch-network/rooch/pull/348#discussion_r1241023169_
            

### We should migrate the new address generating from the resolve function of address_mapping to 

* Option 1: Provide a new function `resolve_or_generate`
* Option 2: Put the generating logic to `ExecutorActor`'s rust code.

### How to generate a new rooch address from a multi-chain address?

* Option 1: hash(multi-chain address)
* Option 2: Case by case.  such as for eth, we can use the original eth address and padding zero before the address.

**Comment by jolestar** [comment]
@yubing744 @wow-sven @feliciss

**Comment by yubing744** [comment]
I tend to Option 1

**Comment by feliciss** [comment]
> We should migrate the new address generating from the resolve function of address_mapping to

I prefer

Option 2: Put the generating logic to ExecutorActor's rust code.

We can add generate_address in Rust code when the mapping record does not exist.

> How to generate a new rooch address from a multi-chain address?

I prefer

Option 2: Case by case. such as for eth, we can use the original eth address and padding zero before the address.

Because there's no common universal solution to hash the multi-chain addresses, such as those using RSA, Diffie-Hellman, ECC signatures, I believe?

**Comment by jolestar** [comment]
Solution:

1. Provide a new function, `resolve_or_generate`, and keep the address generating logic in Move.
2. Generate the rooch address via `hash(multi-chain address)`, for simpler. if we want to keep the original address, we can refactor it after we define the Token standard and Token mapping.
