### ISSUE TITLE
Display problem on mobile phone: cannot hide template 

### ISSUE THREAD

**Issue by geometryolife** [rooch-network/rooch#496]
![image](https://github.com/rooch-network/rooch/assets/54882546/06cd8eba-1d1c-4ce2-a091-d147ecb477fa)

**Comment by Elitexv** [comment]
![Screenshot from 2023-07-18 06-51-00](https://github.com/rooch-network/rooch/assets/46462325/2e9f0ab5-fb70-48de-ade8-bd4c5c776c28)

i thing the error is comming from the folder name (blog-template), maybe it should be renamed rooch reports since it contain weekly report, the blog template displays only on mobile seems its hidden on larger screen sizes

**Comment by Mine77** [comment]
@wow-sven  can you take a look when you have time?
