### ISSUE TITLE
Question: Cross-chain or Multichain

### ISSUE THREAD

**Issue by yng17b** [rooch-network/rooch#536]
Is assets “native assets” or “cross assets” on Rooch? If it's cross assets, I think we should rather call it cross-chain settlement

**Comment by templexxx** [comment]
@yng17b 

Answer： Multi-Chain

It's true that it's as you say from an asset perspective, but we're looking at it from a modular blockchain perspective.

In modular blockchain, we have settlement layer for asserts transfer. And in Rooch, we could support asserts from more than one Layer1, that's why we call it multi-chain settlement.
