### ISSUE TITLE
[SessionKey] Invalid session key when rotate authentication key

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#583]
When the user rotates the authentication key, invalidate all session keys.

1. Which authentication key? The ed25519 authentication key or all authentication keys.
2. How to invalidate all session keys? Provide a function to remove `Table<K:drop, V:drop>`?

**Comment by feliciss** [comment]
1. It depends on the application. If separate dapp needs to work with different auth keys, then we need to invalidate session keys every time when switching dapps.
If not, I think it's the ed25519 auth key if it were to be rotated and the session keys to be invalided. The reason is that the ed25519 works like a master key in functioning of the address generation and management. Here's my quick thoughts on authentication keys and account storage:

![Untitled-2023-07-22-0953-2](https://github.com/rooch-network/rooch/assets/22887031/338fafaa-496f-4a8a-88e6-382ac1e8c487)

**Comment by jolestar** [comment]
In the design, SessionKey will support all built-in schemes. Or do we just support the ed25519 session key?  @baichuan3 @wow-sven

**Comment by baichuan3** [comment]
> In the design, SessionKey will support all built-in schemes. Or do we just support the ed25519 session key? @baichuan3 @wow-sven

Considering that the rooch address only supports ed25519, session key should only support session key in ed25519 format
