### ISSUE TITLE
[Framework] event implementation

### ISSUE THREAD

**Issue by baichuan3** [rooch-network/rooch#91]
Design and implement the event mechanism of rooch framework.
  
**1、aptos and starcoin event style**
```
    struct EventHandle<phantom T: drop + store> has store {
        /// Total number of events emitted to this event stream.
        counter: u64,
        /// A globally unique ID for this event stream.
        guid: GUID,
    }
```
[https://aptos.dev/concepts/events/](url)

Aptos event storage structure K-V
```
K: txn_info_id: HashValue,
V: events: Vec<Event>,
```

Starcoin event storage structure K-V, using an EventKey (sender address + counter) to express a global uuid.
```
K: txn_info_id: HashValue,
V: events: Vec<Event>,
```

**2、sui event style**
```
module sui::event {
    /// Emit a custom Move event, sending the data offchain.
    ///
    /// Used for creating custom indexes and tracking onchain
    /// activity in a way that suits a specific application the most.
    ///
    /// The type T is the main way to index the event, and can contain
    /// phantom parameters, eg emit(MyEvent<phantom T>).
    public native fun emit<T: copy + drop>(event: T);
}
```

```
/// Every MoveEvent has the following properties:
///  - sender
///  - type signature (`T`)
///  - event data (the value of `T`)
///  - timestamp (local to a node)
///  - transaction digest
```

https://docs.sui.io/build/event_api

Sui event storage structure K-V, 
```
DBMap<(TransactionEventsDigest, usize), Event>
```

And using an ```EventID {
                tx_digest,
                event_seq,
            } ``` to express a global uuid.

Rooch event data structure:
/// Every MoveEvent has the following properties:
///  - sender
///  - type signature (`T`)
///  - event data (the value of `T`)
///  - timestamp (local to a node)

TODO: 
1. Is it necessary to maintain the global event uuid in the contract? and certificate is necessary?
    where to storage  event root?  
    every transaction has a merkle tree
    ethereum event implement
3. event filter dimension, by sender? by event key/event id? by MoveEvent?
4. use Object as Storage

**Comment by wubuku** [comment]
If we adopt the Aptos/Starcoin-style event mechanism implementation, I think we can also consider making some improvements, such as removing the counter field from EventHandle and making it an immutable object right after creation.

It may be necessary to give each event a unique ID. So, can we consider having Rooch provide a native method to obtain [UUIDs](https://en.wikipedia.org/wiki/Universally_unique_identifier)?

I believe there are many use cases for UUIDs. Many language runtimes/frameworks also provide implementations for UUIDs.

---

A few more words to say below.

One of the use cases for Rooch is Sovereign Rollup: Rooch + DA. My expectation is that, at the very least, in this case, Rooch should have the ability to achieve a TPS for well-designed Dapps that is more than an order of magnitude higher than Sui (300k TPS on testnet), reaching the level needed for mainstream Web2 internet applications. Of course, the prerequisite is that the Dapp project team needs resources to stack machines, which means that if the project team is not short of money, the technical infrastructure should not be a hindrance.

Based on these expectations, we need to carefully examine the design of the Move Frameworks of existing public chains (Aptos / Starcoin / Sui). The design goals of these L1 public chains are very different from Rooch, as they do not aim to be a general execution container for Dapp applications.

Traditional Web2 applications have many successful experiences in optimizing performance. When Dapp developers need to use these experiences, the technical infrastructure should provide them with assistance rather than creating obstacles for them.

Although some implementation code of the event mechanism is in the Move Framework, it more or less involves native functions, and the infrastructure needs to provide special support for the event mechanism.

One way that traditional Web2 applications improve TPS is by avoiding concurrent operations on the same record in the database to avoid the creation of "hot spots".

**Comment by wubuku** [comment]
One of the main challenges in implementing "Providing UUID" here could be that the UUID cannot be a simple random UUID, but must be generated using a deterministic algorithm. Moreover, it is preferable for the generation algorithm to bypass the consensus process and not make use of shared objects.

To generate a unique UUID, it may be necessary to obtain some information from the current transaction context. If that is not enough, the caller may need to provide additional information to collaboratively ensure the uniqueness of the generated UUID. The responsibility for ensuring the uniqueness of the UUID generated may involve the caller providing additional information to the generation process.

The UUID cannot be used as a random number; its primary purpose is to achieve uniqueness.

**Comment by wubuku** [comment]
I think that the "verifying events" on a blockchain may be more important than proof of state. (Using the term "event proof" may narrow one's perception to assume that the solution must involve verifying events based on a root.)

An event, as a fact that has already occurred, has an immutable character. Using immutable objects can be optimized in code. Event-driven architecture is an inevitable choice for scalable systems. The implementation of eventual consistency for long transactions always depends on the use of events.

Overall, I think the priority for implementing "verifying events" should be higher than state proof.

Implementing “verifying events” may not necessarily require the use of a state root that is updated synchronously during transaction execution, is that correct?

**Comment by baichuan3** [comment]
prepare to implement event based on rooch object as storage, so need  immutable object，which has discussed in https://github.com/rooch-network/rooch/pull/81 @jolestar @wubuku

**Comment by jolestar** [comment]
I think the `event` should not be the state of the contract?

**Comment by jolestar** [comment]
Starcoin/Aptos events can scan all events with an EventKey type. so every Event type needs to maintain a sequence number.

Do you think the DApp needs this feature? @wubuku 

I record on tomorrow's dev meeting  https://docs.google.com/document/d/1bkyMgiJg43KNjF-_XzcuFJB-ySWjzfQV61rwRdN4hQk

**Comment by Mine77** [comment]
Switchboard Oracle:
Aptos
https://docs.switchboard.xyz/api/next/aptos.js/class/AptosEvent#onTrigger
https://github.com/switchboard-xyz/sbv2-aptos/blob/6f02d57d4aa2fadcb28504120b7899d35e6dc854/javascript/aptos.js/src/sbv2.ts#L550

Sui
https://docs.switchboard.xyz/api/next/sui.js/class/SuiEvent
https://github.com/switchboard-xyz/sbv2-sui/blob/e5582dd43c57dff34e6172c474cb0422883d0bea/javascript/sui.js/src/sbv2.ts#L745

**Comment by jolestar** [comment]
Rooch also needs the TransactionInfo. So I think we can put the event Merkle root to the TransactionInfo.

**Comment by baichuan3** [comment]
> How about refer to some projects who could rely on the event service? E.g. Switchboard Oracle: Aptos https://docs.switchboard.xyz/api/next/aptos.js/class/AptosEvent#onTrigger https://github.com/switchboard-xyz/sbv2-aptos/blob/6f02d57d4aa2fadcb28504120b7899d35e6dc854/javascript/aptos.js/src/sbv2.ts#L550
> 
> Sui https://docs.switchboard.xyz/api/next/sui.js/class/SuiEvent https://github.com/switchboard-xyz/sbv2-sui/blob/e5582dd43c57dff34e6172c474cb0422883d0bea/javascript/sui.js/src/sbv2.ts#L745

Feedback is very useful, in Switchboard Oracle's SDK, for both Aptos and Sui, supports obtaining events according to MoveStructTag (that is, type signature T), and supports pagination.

**Comment by baichuan3** [comment]
> https://fullnode.devnet.aptoslabs.com/v1/spec#/operations/get_events_by_event_handle

[suix_queryEvents](https://docs.sui.io/sui-jsonrpc#suix_queryEvents) relying on the indexer implementation, the requirement of querying by event handler is relatively common

**Comment by baichuan3** [comment]
Originally designed according to the sui event style, the contract does not contain guid at all, which is the simplest and more intuitive for developers.

However, when implementing native event, it is found that to implement an event mechanism similar to Sui, it is necessary to expand the existing Move VM virtual machine to implement a runtime event adapter. 

The current transaction is based on the native Move VM, and the transaction and event are bound, which means that to expand the Event, it needs to be connected with the transaction, and the cost of implementation is very high.

Sui achieves a similar effect based on ObjectRuntime,  Its transactions and events are generated based on ObjectRuntime.

Events are related to the following two interfaces of the Move VM core:

1. Save event in native function: 
```
context.save_event(guid, seq_num, ty, msg)
```

2. Derived events after the transaction is executed:
```
let (change_set, raw_events, mut extensions) = session.finish_with_extensions()?;
```

**Comment by baichuan3** [comment]
complete via  https://github.com/rooch-network/rooch/pull/197 and https://github.com/rooch-network/rooch/pull/222
