### ISSUE TITLE
[Object] How to determine whether an ObjectID is a certain type of Object

### ISSUE THREAD

**Issue by WGB5445** [rooch-network/rooch#962]
When we get an Object ID, there seems to be no way to get the relationship between the ID and the Object type.

Currently it can only be determined through borrow:
```
public fun assert_collection_exist_of_id(collectionID: ObjectID, ctx: &mut Context){
        assert!( context::exist_object(ctx, collectionID), ECollectionNotExist);
        context::borrow_object<Collection>(ctx,collectionID);
    }
```

We may need a function to determine whether the ID is of a certain type:
```
function signature:
public fun check<T>(ctx: &mut Context, objectid: ObjectID): bool 

use: 
   context::check<T>(ctx, ObjectID);

```

**Comment by jolestar** [comment]
`exist_object` only cares about the ID, and does not care about the Type.

We can make the `exist_object` care the Type, but 

If object_id exists but not the type T, should `exist_object<T>(object_id)` return false?

**Comment by baichuan3** [comment]
> `exist_object` only cares about the ID, and does not care about the Type.
> 
> We can make the `exist_object` care the Type, but
> 
> If object_id exists but not the type T, should `exist_object<T>(object_id)` return false?

Would it be better to provide two functions that can be combined by user?

**Comment by WGB5445** [comment]
> > `exist_object` only cares about the ID, and does not care about the Type.
> > We can make the `exist_object` care the Type, but
> > If object_id exists but not the type T, should `exist_object<T>(object_id)` return false?
> 
> Would it be better to provide two functions that can be combined by user?

From a usage perspective, exist_object<T>(object_id) should be provided

Because users should know what type their Object is

**Comment by jolestar** [comment]
> Would it be better to provide two functions that can be combined by user?

How to name it? It is too complex for the user. We need to decide by the scenario.

1. In the Table case, the user only cares about if the key exists and does not care about the value Type. Because the user will check if the key exists and then add the key-value pair. If the `raw_table::contains(key)` care about the value type, will cause an error.

2. In the Object case, the ObjectID is generated via the system. The user can not construct the ObjectID, so the `exist_object<T>(object_id)` can care about the value type. But the `raw_table` implemention needs to refactor.

How about private a native function `raw_table::borrow_option<T>(key):&Option<T>`? and implement the `contains` function in Move.

**Comment by jolestar** [comment]
The `key_layout` is for serializing the `Key` to `vec<u8>`, and putting it in  `content: BTreeMap<Vec<u8>, TableRuntimeValue>`. The value_layout in `TableRuntimeValue`.

**Comment by jolestar** [comment]
use `exists_object_with_type<T: key>(object_id: ObjectID): bool`

https://github.com/rooch-network/rooch/blob/85b9502e307cee0d7ecc3f51e2b7d07ea7da2e6b/frameworks/moveos-stdlib/sources/object.move#L235-L237
